### ISSUE TITLE
openvpn-pihole: pi-hole v4.1.1 error 'Starting pihole-FTL (no-daemon) with kill: usage: kill [-s sigspec

### ISSUE THREAD

**Issue by mr-bolle** [mr-bolle/docker-compose#1]
Since the pi-hole 4.1.1. i get follow error message

```
vpn_pihole | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
vpn_pihole | Starting pihole-FTL (no-daemon)

```

**Comment by mr-bolle** [comment]
fix this follow change https://github.com/mr-bolle/docker-compose/commit/adc63d8d626619f5d3e12558e65131c1b1219232

thank you Adam Hill for your support

```
   pihole:
     cap_add:
       - NET_ADMIN
     environment:
       - DNS1=127.0.0.1     # necessarry 
       - DNS2=1.1.1.1         # custom change possible
```
